version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: macedonian_grammarly_db
    restart: always
    environment:
      POSTGRES_USER: janasandra
      POSTGRES_PASSWORD: janasandra123
      POSTGRES_DB: grammarlydb
    ports:
      - "5432:5432"
    volumes:
      - grammarly-data:/var/lib/postgresql/data

volumes:
  grammarly-data:
